### PR TITLE
feat: enable monitoring

### LINKED ISSUE #108: Add monitoring configuration to CNPG
**What**
I've disabled `PodMonitor`, as it requires enabling the Grafana and Prometheus charts:

https://cloudnative-pg.io/documentation/1.23/quickstart/#part-4-monitor-clusters-with-prometheus-and-grafana

In order to properly assist customers in a BYOC environment, we should reenable those so we can export logs over (at least Prometheus logs) that we can plot to see what's wrong.

**Why**
^

**How**
See the link I shared

### PR DESCRIPTION
**Pull request by vaibhawvipul**
# Ticket(s) Closed

- Closes #108 

## What
- enable monitoring

## How
- adding postgresExporter
- add alets

### CODE REVIEW

**Review by philippemnoel — COMMENTED** [review]
@itay-grudev I'll defer to you on reviewing/approving this PR

**Comment by itay-grudev** [comment]
There is already support for this in the official chart. If we fork it we'll get this functionality through it. There is an elaborate [default monitoring ConfigMap](https://github.com/cloudnative-pg/cloudnative-pg/blob/0d3358aa36f536f89f9e86f7f888b7a20cb84bc1/config/manager/default-monitoring.yaml) there which covers most if not all that is specified here. I'll go through yours and verify that all that you've included is available upstream. If not I'll either add it to your fork of the chart or upstream.

**Comment by philippemnoel** [comment]
> There is already support for this in the official chart. If we fork it we'll get this functionality through it. There is an elaborate [default monitoring ConfigMap](https://github.com/cloudnative-pg/cloudnative-pg/blob/0d3358aa36f536f89f9e86f7f888b7a20cb84bc1/config/manager/default-monitoring.yaml) there which covers most if not all that is specified here. I'll go through yours and verify that all that you've included is available upstream. If not I'll either add it to your fork of the chart or upstream.

Just focus on the upstream one, this is just an attempt at doing this ourselves which we probably shouldn't do

**Comment by philippemnoel** [comment]
Closing, we are moving to https://github.com/paradedb/charts

**Pull request closed without merging**
